Repository fairyglade/ly, pull requests merged in 2023-06, with the labels that each got.

#479 Tidy up runit service scripts
  makefile
  readme.md
  res/ly-runit-service/conf
  res/ly-runit-service/finish
  res/ly-runit-service/run
Labels: bug, needs review

#251 Add location of Xresources for XDG Base Dir Spec
  res/xsetup.sh
Labels: ok, needs review

#461 Clocks
  res/config.ini
  src/bigclock.h
  src/config.c
  src/config.h
  src/draw.c
  src/draw.h
  src/main.c
Labels: feature

#487 Change default keybindings F1/F2 to F12/F11.
  readme.md
  res/config.ini
  res/lang/cat.ini
  res/lang/cs.ini
  res/lang/de.ini
  res/lang/en.ini
  res/lang/es.ini
  res/lang/fr.ini
  res/lang/it.ini
  res/lang/pl.ini
  res/lang/pt.ini
  res/lang/pt_BR.ini
  res/lang/ro.ini
  res/lang/ru.ini
  res/lang/sr.ini
  res/lang/sv.ini
  res/lang/tr.ini
  res/lang/uk.ini
  src/config.c
  src/config.h
  src/draw.c
  src/draw.h
  src/main.c
Labels: feature
